    spring.application.name=banking-api

    # ==========================================
    # DATABASE CONFIGURATION
    # ==========================================
    spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    spring.datasource.username=${DB_USER}
    spring.datasource.password=${DB_PASSWORD}
    spring.datasource.driver-class-name=org.postgresql.Driver


    # ==========================================
    # HIKARI CONNECTION POOL (Optional tuning)
    # ==========================================
    spring.datasource.hikari.minimum-idle=5
    spring.datasource.hikari.maximum-pool-size=10
    spring.datasource.hikari.idle-timeout=30000
    spring.datasource.hikari.pool-name=BankHikariPool

    # ===========================================
    # SERVER CONFIGURATION
    # ===========================================
    server.port=8080


    # ===========================================
    # Logging (To see SQL queries in console)
    # ===========================================
    #logging.level.org.springframework.jdbc=DEBUG
    #logging.level.com.bank=DEBUG


    # ===========================================
    # ACTUATOR CONFIGURATION
    # ===========================================
    # Expose health, info, prometheus, AND metrics endpoints
    management.endpoints.web.exposure.include=health,info,prometheus,metrics

    # Explicitly enable the metrics endpoint (sometimes required depending on Spring Boot version)
    management.endpoint.metrics.enabled=true

    # Show detailed health information only when authorized
    management.endpoint.health.show-details=when-authorized


    # Flyway
    spring.flyway.enabled=true
    spring.flyway.locations=classpath:db/migration
    # Baselining: treat existing database as version 1 and skip V1__init.sql
    spring.flyway.baseline-on-migrate=true
    spring.flyway.baseline-version=1

    #logging.level.org.flywaydb=DEBUG



    # Authentication KEY
    spring.config.import=optional:file:.env[.properties]