# ==========================================
# PRODUCTION CONFIGURATION
# ==========================================
spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===========================================
# SERVER CONFIGURATION
# ===========================================
server.port=8080
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s


# ==========================================
# DATABASE CONFIGURATION (Will be overridden by environment variables)
# ==========================================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false


# ==========================================
# HIKARI CONNECTION POOL (Optional tuning)
# ==========================================
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=BankHikariPool
spring.datasource.hikari.connection-timeout=20000

# ==========================================
# TOMCAT THREAD POOL
# ==========================================
server.tomcat.threads.max=200
server.tomcat.threads.min-spare=20
server.tomcat.accept-count=100

# ==========================================
# ACTUATOR (Health Checks)
# ==========================================
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.health.redis.enabled=false
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.sla.http.server.requests=10ms,50ms,100ms,200ms,500ms,1s,2s
management.metrics.tags.application=banking-api
management.metrics.enable.hikaricp=true
management.metrics.enable.jvm=true


# ==========================================
# LOGGING (Production Level)
# ==========================================
logging.level.root=INFO
logging.level.com.bank=INFO
logging.level.org.springframework.jdbc=WARN
logging.level.org.hibernate.SQL=WARN
logging.level.org.flywaydb=INFO


# ==========================================
# FLYWAY
# ==========================================
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=6379
spring.data.redis.timeout=100ms
spring.data.redis.connect-timeout=100ms
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.cache.type=redis
spring.cache.redis.time-to-live=60000
spring.cache.redis.cache-null-values=false
